export const minesData = [
  {
      "name": "AMALGAMATED KESHALPUR\nWEST MUDIDIH COLLIERY\n(AKWMC)",
      "latitude": 23.8078,
      "longitude": 86.3221,
      "state": "Jharkhand",
      "district": "Dhanbad",
      "mine_type": "Mixed",
      "owner": "BCCL",
      "govtprivate": "G",
      "image": "/CoalMines/AKWMC/image.png",
      "summary":"../CoalMines/AKWMC",
  },
  {
      "name": "PHULARITAND",
      "latitude": 23.782,
      "longitude": 86.2229,
      "state": "Jharkhand",
      "district": "Dhanbad",
      "mine_type": "UG",
      "owner": "BCCL",
      "govtprivate": "G",
      "image": "/CoalMines/PHULARITAND/image.png",
      "summary":"../CoalMines/PHULARITAND",
  },
  {
      "name": "KUYA /KOCP",
      "latitude": 23.7363,
      "longitude": 86.4498,
      "state": "Jharkhand",
      "district": "Dhanbad",
      "mine_type": "OC",
      "owner": "BCCL",
      "govtprivate": "G",
      "image": "/CoalMines/KuyaKocp/image.png",
      "summary":"../CoalMines/KuyaKocp",
  },
  {
      "name": "NEW AKASH KINAREE COLLY\n(NAKC)",
      "latitude": 23.8079,
      "longitude": 86.2843,
      "state": "Jharkhand",
      "district": "Dhanbad",
      "mine_type": "Mixed",
      "owner": "BCCL",
      "govtprivate": "G",
      "image": "/CoalMines/NEW-AKASH/image.png",
      "summary":"../CoalMines/NEW-AKASH",

  },
  {
      "name": "NEW GODHUR. KUSUNDA\nCOLLIERY",
      "latitude": 23.7885551985198,
      "longitude": 86.3919124940458,
      "state": "Jharkhand",
      "district": "Dhanbad",
      "mine_type": "UG",
      "owner": "BCCL",
      "govtprivate": "G",
      "image": "/CoalMines/GODHUR-KUSUNDA/image.png",
      "summary":"../CoalMines/GODHUR-KUSUNDA",

  },
  {
      "name": "CHORA BLOCK INCLINE,\nSHANKARPUR OC &\nBONBAHAL OC",
      "latitude": 23.6729,
      "longitude": 87.2033,
      "state": "West Bengal",
      "district": "Paschim Bardhaman",
      "mine_type": "Mixed",
      "owner": "ECL",
      "govtprivate": "G",
      "image": "/CoalMines/CHORA-BLOCK/image.png",
      "summary":"../CoalMines/CHORA-BLOCK",

  },
  {
      "name": "BANSRA",
      "latitude": 23.6296,
      "longitude": 87.1382,
      "state": "West Bengal",
      "district": "Paschim Bardhaman",
      "mine_type": "Mixed",
      "owner": "ECL",
      "govtprivate": "G",
      "image": "/CoalMines/BANSRA/image.png",
      "summary":"../CoalMines/BANSRA",

  },
  {
      "name": "TETULMARI",
      "latitude": 23.8034,
      "longitude": 86.345,
      "state": "Jharkhand",
      "district": "Dhanbad",
      "mine_type": "UG",
      "owner": "BCCL",
      "govtprivate": "G",
      "image": "/CoalMines/TETULMARI/image.png",
      "summary":"../CoalMines/TETULMARI",

  },
  {
      "name": "BHANORA W/B (UG & OC)",
      "latitude": 23.7276,
      "longitude": 86.9943,
      "state": "West Bengal",
      "district": "Paschim Bardhaman",
      "mine_type": "UG",
      "owner": "ECL",
      "govtprivate": "G",
      "image": "/CoalMines/BHANORA-WB/image.png",
      "summary":"../CoalMines/BHANORA-WB",

  },
  {
      "name": "GEVRA OC",
      "latitude": 22.3308,
      "longitude": 82.5958,
      "state": "Chhattisgarh",
      "district": "Korba",
      "mine_type": "OC",
      "owner": "SECL",
      "govtprivate": "G",
      "image": "/CoalMines/Gevra-Open-Cast/image.png",
      "summary":"../CoalMines/Gevra-Open-Cast",

  },
  {
      "name": "KUSMUNDA",
      "latitude": 22.3067,
      "longitude": 82.6732,
      "state": "Chhattisgarh",
      "district": "Korba",
      "mine_type": "OC",
      "owner": "SECL",
      "govtprivate": "G",
      "image": "/CoalMines/KUSMUNDA/image.png",
      "summary":"../CoalMines/KUSMUNDA",

  },
  {
      "name": "BHUBANESWARI",
      "latitude": 20.9725,
      "longitude": 85.1732,
      "state": "Orissa",
      "district": "Angul",
      "mine_type": "OC",
      "owner": "MCL",
      "govtprivate": "G",
      "image": "/CoalMines/BHUBANESWARI/image.png",
      "summary":"../CoalMines/BHUBANESWARI",

  },
  {
      "name": "DIPKA",
      "latitude": 22.3225,
      "longitude": 82.5363,
      "state": "Chhattisgarh",
      "district": "Korba",
      "mine_type": "OC",
      "owner": "SECL",
      "govtprivate": "G",
      "image": "/CoalMines/DIPKA/image.png",
      "summary":"../CoalMines/DIPKA",

  },
  {
      "name": "LAKHANPUR",
      "latitude": 21.7451,
      "longitude": 83.8401,
      "state": "Orissa",
      "district": "Jharsuguda",
      "mine_type": "OC",
      "owner": "MCL",
      "govtprivate": "G",
      "image": "/CoalMines/Lakhanpur/image.png",
      "summary":"../CoalMines/Lakhanpur",

  },
  {
      "name": "NIGAHI",
      "latitude": 24.1539,
      "longitude": 82.6322,
      "state": "Madhya Pradesh",
      "district": "Singrauli",
      "mine_type": "OC",
      "owner": "NCL",
      "govtprivate": "G",
      "image": "/CoalMines/Nigahi/image.png",
      "summary":"../CoalMines/Nigahi",

  },
  {
      "name": "JAYANT",
      "latitude": 24.151,
      "longitude": 82.6579,
      "state": "Madhya Pradesh",
      "district": "Singrauli",
      "mine_type": "OC",
      "owner": "NCL",
      "govtprivate": "G",
      "image": "/CoalMines/Jayant/image.png",
      "summary":"../CoalMines/Jayant",


  },
  {
      "name": "Mohar & Moher-Amlori Extension Coal Mine",
      "latitude": 24.1358,
      "longitude": 82.5915,
      "state": "Madhya Pradesh",
      "district": "Singrauli",
      "mine_type": "OC",
      "owner": "NCL",
      "govtprivate": "G",
      "image": "/CoalMines/mohar-moher/image.png",
      "summary":"../CoalMines/mohar-moher",

  },
  {
      "name": "DUDHICHUA",
      "latitude": 24.1515,
      "longitude": 82.6929,
      "state": "Uttar Pradesh",
      "district": "Sonebhadra",
      "mine_type": "OC",
      "owner": "NCL",
      "govtprivate": "G",
      "image": "/CoalMines/Dudhichua/image.png",
      "summary":"../CoalMines/Dudhichua",

  },
  {
      "name": "Jhanjhara Project Colly",
      "latitude": 23.668,
      "longitude": 87.2963,
      "state": "West Bengal",
      "district": "Paschim Bardhaman",
      "mine_type": "UG",
      "owner": "ECL",
      "govtprivate": "G",
      "image": "/CoalMines/Jhanjhara/image.png",
      "summary":"../CoalMines/Jhanjhara",
      
  },
  {
      "name": "ALP",
      "latitude": 18.6648,
      "longitude": 79.579,
      "state": "Telangana",
      "district": "Mancherial",
      "mine_type": "UG",
      "owner": "SCCL",
      "govtprivate": "SG",
      "image": "/CoalMines/ALP/image.png",
      "summary":"../CoalMines/ALP",

  },
  {
      "name": "CHURCHA RO",
      "latitude": 23.3342,
      "longitude": 82.52,
      "state": "Chhattisgarh",
      "district": "Koriya",
      "mine_type": "OC",
      "owner": "SECL",
      "govtprivate": "G",
      "image": "/CoalMines/charcha-chattisgarh/image.png",
      "summary":"../CoalMines/charcha-chattisgarh",


  },
  {
      "name": "SHARDA HIGHWALL",
      "latitude": 23.2084,
      "longitude": 81.5896,
      "state": "Madhya Pradesh",
      "district": "Shahdol",
      "mine_type": "OC",
      "owner": "SECL",
      "govtprivate": "G",
      "image": "/CoalMines/SHARDA-HIGHWALL/image.png",
      "summary":"../CoalMines/SHARDA-HIGHWALL",

  },
  {
      "name": "\u00a0SHYAMSUNOERPUR\u00a0",
      "latitude": 23.6483,
      "longitude": 87.2575,
      "state": "West Bengal",
      "district": "Paschim Bardhaman",
      "mine_type": "UG",
      "owner": "ECL",
      "govtprivate": "G",
      "image": "/CoalMines/Shyamsunorpur/image.png",
      "summary":"../CoalMines/Shyamsunorpur",

  },
  {
      "name": "KHAIRAHA",
      "latitude": 23.1543,
      "longitude": 81.4589,
      "state": "Madhya Pradesh",
      "district": "Shahdol",
      "mine_type": "OC",
      "owner": "SECL",
      "govtprivate": "G",
      "image": "/CoalMines/Khairaha/image.png",
      "summary":"../CoalMines/Khairaha",

  },
  {
      "name": "GDK 11 INC",
      "latitude": 18.4161,
      "longitude": 79.3258,
      "state": "Telangana",
      "district": "Peddapalli",
      "mine_type": "UG",
      "owner":"SCCL",
      "govtprivate":"SG",
      "image": "/CoalMines/GDK/image.png",
      "summary":"../CoalMines/GDK",


  },
  {
      "name": "HALDIBARI",
      "latitude": 23.2232,
      "longitude": 82.1501,
      "state": "Chhattisgarh",
      "district": "Korea",
      "mine_type": "UG",
      "owner":"SECL",
      "govtprivate":"G",
      "image": "/CoalMines/haldibari/image.png",
      "summary":"../CoalMines/haldibari",

    },
    {
      "name": "BANGWAR\u00a0",
      "latitude": 23.1542,
      "longitude": 81.5361,
      "state": "Madhya Pradesh",
      "district": "Shahdol",
      "mine_type": "UG",
      "owner":"SECL",
      "govtprivate":"G",
      "image": "/CoalMines/Bangwar/image.png",
      "summary":"../CoalMines/Bangwar",

    }

]
